# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):

    obj = bld.create_ns3_program('residential-example', ['core', 'network', 'docsis'])
    obj.source = 'residential-example.cc'

    obj = bld.create_ns3_program('docsis-configuration-example', ['core', 'network', 'docsis'])
    obj.source = 'docsis-configuration-example.cc'

